### Makefile --- 

## Author: 
## Version: $Id: Makefile,
## Keywords: 
## X-URL: 
## description: 

# seeds-java: seeds-config seeds-uc seeds-gateway seeds-admin seeds-game 

apply:
	kubectl apply -k ./mysql-nfs-kustomiz/

delete:
	kubectl delete -k ./mysql-nfs-kustomiz/
