---

#对外服务
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
  labels:
    app: mysql-test
spec:
  type: NodePort
  selector:
      app: mysql-test
  ports:
  - protocol : TCP
    nodePort: 30307
    port: 3307
    targetPort: 3306
---

#有状态服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-test
spec:
  replicas: 1
  serviceName: mysql-test
  selector:
    matchLabels:
      app: mysql-test
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
      containers:
      - name: mysql-test
        image: harbor.seedslabs.io/seeds-db/mysql8:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Seeds123!
        resources:
          requests:
            cpu: "50m"
            memory: 1Gi
          limits:
            cpu: "200m"
            memory: 2Gi
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 30
        volumeMounts:
        - name: mysql-test-storage
          mountPath: /var/lib/mysql
          subPath: mysqldata
      nodeSelector:
        usefulness: nfs-provisioner
      imagePullSecrets:
        - name: harbor-uat
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata: 
      name: mysql-test-storage
    spec: 
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs-client"
      # storageClassName: "standard-rwo"
      resources: 
        requests:
          storage: 20Gi