---

#对外服务
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
      app: mysql
  ports:
  - protocol : TCP
    nodePort: 30306
    port: 3306
    targetPort: 3306
---

#有状态服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: harbor.seedslabs.io/seeds-db/mysql8:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Seeds123!
        # resources:
        #   requests:
        #     cpu: "50m"
        #     memory: 1Gi
        #   limits:
        #     cpu: "200m"
        #     memory: 2Gi
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 15
        #   failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 30
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
          # subPath: mysqldata
      nodeSelector:
        useful: mysql
      imagePullSecrets:
        - name: harbor-uat
      # terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata: 
      name: mysql-storage
    spec: 
      accessModes: ["ReadWriteOnce"]
      storageClassName: "nfs-client"
      resources: 
        requests:
          storage: 20Gi