version: '3.7'
services:
  iot-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    hostname: iot-server
    container_name: iot-server
    image: iot-java:11
    ports:
      - 8080:8080
      - 1883:1883
      - 7070:7070
    volumes:
      - /etc/localtime:/etc/localtime

  nginx:
    # build:
    #   context: ./web
    #   dockerfile: Dockerfile
    restart: always
    container_name: iot-web
    image: iot-web
    network_mode: "host"
    ports:
      - 80:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/iot:/root/iot
    environment:
      - NGINX_PORT=80
    privileged: true