---
# reference: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/
namespace: production
# 这里要指定 ns，否则会将 secret 创建在 ns=default
resources:
- ../base
secretGenerator:
# using literals 
- name: username
  literals:
  - username=admin
# using files 
- name: region
  files:
  - region=region.txt
# using .env
- name: password
  envs:
  - .env