apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: seeds-uat
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 30120
  selector:
    app: redis
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: seeds-uat
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: harbor.seedslabs.io/seeds-db/redis:latest
        command:
          - "sh"
          - "-c"
          - "redis-server /usr/local/redis/redis.conf"
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          # requests:
          #   memory: "250Mi"
          #   cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 30
          # timeoutSeconds: 1
          periodSeconds: 30
          # successThreshold: 1
          # failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          # successThreshold: 1
          # failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath:  /usr/local/redis/redis.conf
          subPath: redis.conf
      imagePullSecrets:
        - name: harbor-uat
      volumes:
      - name: config
        configMap:
          name: redis-config