version: '3.7'
services:

  iot-nginx: 
    image: nginx:1.23.0-alpine
    container_name: iot-nginx
    network_mode: "host"
    restart: always
    volumes:
      - "./dist:/usr/local/nginx/html/dist"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
