version: '3.1'
services:
  frps-server:
    hostname: frps-server
    restart: unless-stopped
    image: ibm-semeru-runtimes:open-8-jre
    container_name: frps-server
    # 不使用打包方式，而是将 frp 程序挂载进容器
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        max-size: "500m"
    ports:
      - 60060:60060
      - 60080:60080
      # - LANPROXY_USERNAME=admin
      # - LANPROXY_PASSWORD=Hlxx@0613385
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frp:/frp
      - ./proxy-server-0.1:/proxy-server
    command:
      - /frp/frps 
      - -c
      - /frp/frps.ini