version: '3.7'
services:
  nexus:
    restart: always
    image: sonatype/nexus3
    container_name: nexus
    network_mode: host
    ports:
      - 8081:8081
    volumes:
      - /home/data/nexus:/nexus-data