apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: vela-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: liuzelin01@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          name: kubevela-ingress