version: '3.7'
services:
  dllng-lng:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: dllng-lng
    image: dllng-java:8
    logging:
      driver: json-file
      options:
        max-size: "5g"
        max-file: "3"
    ports:
      - 9701:9701
    volumes:
      - ./hklinuxlib:/usr/local/hklinuxlib
