---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: production
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: username
              key: username
        - name: REGION
          valueFrom:
            secretKeyRef:
              name: region
              key: region
        - name: PASWD
          valueFrom:
            secretKeyRef:
              name: password
              key: PASSWORD