[Engine]
EnableAudio = true
EnableVideo = true
# 发布流默认过期时间单位秒
PublishTimeout = 60
# 自动关闭触发后延迟的秒数(期间内如果有新的订阅则取消触发关闭)
AutoCloseDelay = 10
# RTP包乱序重排
RTPReorder = false


[Summary]
# 1秒中采样一次
SampleRate = 1


[RTMP]
ListenAddr = ":1935"

[GateWay]
ListenAddr = ":8081"
ListenAddrTLS = ":8082"
CertFile = "server.pem"
KeyFile = "server.key"

[Jessica]
#ListenAddr = ":8081"
#ListenAddrTLS = ":8083"
#CertFile = "xxx.cert"
#KeyFile = "xxx.key"

[LogRotate]
# 日志存储目录相对或绝对
Path = "logs"
# 日志是否按大小分割，0表示不按大小分割，非零代表按该大小字节进行分割
Size = 0
Days = 1
# 按照go layout格式化，默认按照小时
Formatter = "2006-01-02T15"
# [FFMPEG]


[HLS]
# 是否开启写磁盘，开启后侦测到发布流就会开始写TS文件
EnableWrite = false
# 是否打开内存模式，在内存中保留TS数据，方便直接读取
EnableMemory = false
# 分片大小 单位秒
Fragment = 10
# 窗口数里，代表一个m3u8文件里面有几个ts
Window = 2
# ts文件存放目录，m3u8会存放在上一级
Path = "resource"

# 使用文件存储的驱动
#Drive = "fastdfs://172.16.2.13:22122?maxConns=1000"

[HDL]
#ListenAddr = ":2020"
#ListenAddrTLS = ":2021"
#CertFile = "xxx.cert"
#KeyFile = "xxx.key"
#Reconnect = true

[TS]
# ts存放目录
Path = "resource"
[Record]
Path = "resource"
# 自动录制功能
AutoRecord = false


[RTSP]
# 端口接收推流
ListenAddr = ":554"
Reconnect = true

[Repository]
uri = ""

[WebRTC]
# 端口范围不配置的话是自动分配
# PortMin = 30000
# PortMax = 40000
# 公网访问必须配置PublicIP，否则无法建立连接
# PublicIP = ["192.168.1.120"]
# WebRTC 推流时控制GOP大小，单位毫秒
# PLI = 2000


[GB28181]
Serial = "34020000002000000001"
Realm = "3402000000"
Expires = 3600
#ListenAddr = "172.16.100.112:5060"
ListenAddr = "172.16.100.111:5060"
#ListenAddr = "192.168.31.226:5060"
AutoCloseAfter = -1
AutoInvite = true
MediaPort = 58200
CatalogInterval = 30
RemoveBanInterval = 600
#Username = "34020000001320000001"
#Password = "admin123"
UdpCacheSize = 0
TCP = false



[AIService]
Url = "http://127.0.0.1"

#配置转发规则，
#例如需要转发到  http://127.0.0.1:8081/debug/pprof/start
#配置则是：{ Path = "/debug/pprof/start", Host = "http://127.0.0.1:8081" },
#请求时 curl http://server:port/forward/debug/pprof/start
#这里是完全转发到方式，请求头需要自行配置
[Forward]

Forward = [
    { Path = "/aiServer/configuration/monitoring-liveStream", Host = "http://127.0.0.1:30302" },
    { Path = "/aiServer/configuration/monitoring-realTime", Host = "http://127.0.0.1:30303" },
    { Path = "/aiServer/configuration/monitoring", Host = "http://127.0.0.1:30302" },
    { Path = "/aiServer/startWorking/polling", Host = "http://127.0.0.1:30302" },
]

[Snap]
ffmpeg = "C:\\Program Files\\ffmpeg-n5.0-latest-win64-gpl-5.0\\bin\\ffmpeg.exe"
