apply:
	kubectl apply -k ./production

delete:
	kubectl delete -k ./production

get-pod:
	kubectl get po -owide | grep nginx-deployment

# get-cm: 
# 	kubectl get cm -owide | grep 'credentials\|config-'
