# # mysql-deployment-status-scale
# #设置持久卷
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   # namespace: default 
#   labels:
#     app: mysql
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
# ---

#对外服务
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
      app: mysql
  ports:
  - protocol : TCP
    nodePort: 30306
    port: 3306
    targetPort: 3306
---

#有状态服务
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: harbor.seedslabs.io/seeds-db/mysql8:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Seeds123! 
        resources:
          requests:
            cpu: "50m"
            memory: 1Gi
          limits:
            cpu: "200m"
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 30
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
          subPath: mysqldata
      imagePullSecrets:
        - name: harbor-uat
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata: 
      name: mysql-storage
    spec: 
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard-rwo"
      resources: 
        requests:
          storage: 20Gi
  # podManagementPolicy: OrderedReady
  # updateStrategy:
  #   type: RollingUpdate
