apiVersion: v1
kind: Service
metadata:
  # name: service-redis
  name: seeds-admin
  namespace: seeds-uat
spec:
  ports:
    - port: 10102
      targetPort: 10102
      protocol: TCP
  selector:
    app: seeds-admin
  # type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeds-admin
  namespace: seeds-uat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeds-admin
  template:
    metadata:
      labels:
        app: seeds-admin
        # 不同的应用程序层级
        # frontend/backend/database
        tier: backend
    spec:
      containers:
      - name: seeds-admin
        image: harbor.seedslabs.io/seeds-java/seeds-admin:latest
        imagePullPolicy: Always
        env:
        # - name: PROFILE
        #   value: prd
        # - name: BUILD_NUMBER
        #   value: BN_88
        - name: app_name
          value: seeds-admin
        - name: SERVER_PORT
          value: "8888"
        - name: DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/seeds_admin?useUnicode=true&characterEncoding=utf-8
        - name: DATASOURCE_USERNAME
          value: root
        - name: DATASOURCE_PASSWORD
          value: Seeds123!
        - name: CONFIG_SERVERS
          value: http://seeds-config:8888
        # redis 的变量
        ports:
          - containerPort: 10102
        readinessProbe:
          tcpSocket:
            port: 10102
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 10102
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 30
        resources: {}
          # requests:
          #   memory: "512Mi"
          #   cpu: "500m"
          # limits:
          #   # memory: "512Mi"
          #   memory: 1Gi
          #   cpu: 1
      imagePullSecrets:
        - name: harbor-uat