apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeds-uc
  namespace: seeds-uat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeds-uc
  template:
    metadata:
      labels:
        app: seeds-uc
        # 不同的应用程序层级
        # frontend/backend/database
        tier: backend
    spec:
      containers:
      - name: seeds-uc
        image: harbor.seedslabs.io/seeds-java/seeds-uc:latest
        imagePullPolicy: Always
        env:
        # - name: PROFILE
        #   value: prd
        - name: APP_name
          value: seeds-uc
        # - name: BUILD_NUMBER
        #   value: BN_88
        ports:
          - containerPort: 8888
        # readinessProbe:
        #   tcpSocket:
        #     port: 8888
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 30
        # livenessProbe:
        #   tcpSocket:
        #     port: 8888
        #   initialDelaySeconds: 60
        #   periodSeconds: 60
        #   timeoutSeconds: 30
        resources: {}
          # requests:
          #   memory: "512Mi"
          #   cpu: "500m"
          # limits:
          #   memory: "512Mi"
          #   cpu: "1000m"
      imagePullSecrets:
        - name: harbor-uat