# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy: {}

imagePullSecretName:

image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP

persistence:
  enabled: true
  storageClass: standard-rwo
  accessMode: ReadWriteOnce
  size: 20Gi

openvpn:
  OVPN_K8S_POD_NETWORK: "10.148.0.0"
  OVPN_K8S_POD_SUBNET: "255.255.0.0"
  OVPN_K8S_SVC_NETWORK: "10.152.0.0"
  OVPN_K8S_SVC_SUBNET: "255.255.0.0"

  cipher: AES-256-CBC
ipForwardInitContainer: true