apiVersion: v1
kind: Service
metadata:
  name: seeds-config
  namespace: seeds-uat
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: seeds-config
  # type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeds-config
  namespace: seeds-uat 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeds-config
  template:
    metadata:
      labels:
        app: seeds-config
        # 不同的应用程序层级
        # frontend/backend/database
        tier: backend
    spec:
      containers:
      - name: seeds-config
        image: harbor.seedslabs.io/seeds-java/seeds-config:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
        env:
        - name: APP_NAME
          value: seeds-config
        # configure of seeds-config.yml
        # configure of bootstrap.yml
          
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources: {}
          # requests:
          #   memory: "512Mi"
          #   cpu: "500m"
          # limits:
          #   memory: "512Mi"
          #   cpu: "1000m"
      nodeSelector:
        usefulness: seeds
      imagePullSecrets:
        - name: harbor-uat