---
# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list

namePrefix: production-
namespace: production
resources:
- ../../base
- namespace.yml
patchesStrategicMerge:
# 将部署内容，使用同级目录的 deployment.yml overlay 掉
- deployment.yml
