# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list

namePrefix: production-
namespace: production
resources:
- ../../base
- namespace.yml
# 将部署内容，使用同级目录的 deployment.yml overlay 掉
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: deployment.yml
